[package]
name = "push-mock-server"
version = "0.1.0"
authors = ["Jonas Lima <jonaslimads@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
